### ISSUE TITLE
Tiempo infinito de carga en Icestudio 0.4.0

### ISSUE THREAD

**Issue by MrManlu** [Obijuan/RISC-V-FPGA#2]
Ante todo, dar la enhorabuena por el proyecto. Poder "jugar" con un procesador a éste nivel y que funcione en un sistema real es uno de los sueños de cualquier maker.

Por otra parte, no he sido capaz de abrir ningún proyecto de los tres subidos (soc-demo.ice y los dos soc-rars-*.ice). Al abrir Icestudio, tras darle a "Archivo -> Abrir" y seleccionar cualquier proyecto, el programa se mantiene en estado de carga mucho tiempo (más de 10 minutos en mi caso) y no parece arrancar nunca.

Puedo seguir abriendo menús, pero el diseño nunca aparece y el icono del ratón se mantiene indicando que el programa está cargando.

Estoy utilizando Ubuntu 18.04.3 LTS (64 bits), Python 2.7.15+ y 3.6.8, e Icestudio v0.4.0.

¡Muchas gracias por tu tiempo! Un saludo desde Sevilla.

**Comment by MrManlu** [comment]
PD: He probado con la versión v0.5.0-dev y es capaz de abrir correctamente los archivos. No sé a qué se deberá esta diferencia.

**Comment by Obijuan** [comment]
Esos ficheros usan etiquetas, que es una característica que No está en
icestudio 0.4. No podrás abrirlos con la 0.4,sólo a partir de la 0.5 o
superioir

En breve la 0.5 será la nueva versión estable

**Comment by MrManlu** [comment]
Estupendo, muchísimas gracias!
