### ISSUE TITLE
Update for newest icestudio

### ISSUE THREAD

**Issue by garretraziel** [Obijuan/RISC-V-FPGA#6]
I've tried syntetizing this project in different versions of icestudio and the last that worked for me was icestudio 0.6.0; after that, icestudio returns errors; icestudio 0.9.0-rc1 returns:

``main.v:374: error: `endif without a matching `ifdef.``

I'm not sure if this is error with a project, or with icestudio (but it's happening also with the stable versions).

**Comment by Obijuan** [comment]
Bug confirmed

Since icestudio 0.7 the toolchains were updated. The new toolchains detect an error that the previous didn't. I will work on it  
Thanks for testing and reporting the bug 😃️

**Comment by Obijuan** [comment]
It should be fixed now. Please, try it and confirm that you can build the circuit without any error

**Comment by garretraziel** [comment]
I've tried your fix and verification, building and upload now works (in icestudio 0.9.0-rc1), but as soon as the RISC-V processor is uploaded to my Alhambra II board, first five leds go on; when I then upload sample risc-v program (from firmware/soc-demo/src-c), it does nothing (nothing is shown in serial console, there is no binary led counter). I'm testing this on aarch64 on my Raspberry Pi though, so perhaps it could be caused by bad synthesis?

**Comment by garretraziel** [comment]
I have verified this on my Mac Mini; the behaviour is strange. It seems that the newest code, when uploaded using Icestudio 0.6.0, works without problem; when I try to compile project using Icestudio 0.9.0-rc1, it compiles and is successfully uploaded to Alhambra II, but then first 4 leds turn on (as if there were leds-on.bin program uploaded) and even if I program it with test.bin, instead of led counter, just those 4 leds are still on. So either there is a problem with iceprog (but it reports that it uploaded code without problem) or there is still a bug in compiling RISC-V with the latest Icestudio :-/.

**Comment by Obijuan** [comment]
I've fixed the UART. It was not working ok with the latest toolchain. Now it should work ok. Please, try it and confirm that the test.bin firmware is working as expected (the counter should be shown on the leds, and the messages on the serial terminal)  
You can also test it with the icestudio serial terminal (so that it is not necessary to install other)

**Comment by garretraziel** [comment]
Uh, sorry to still be a bother, but I think there is still something off. test.bin now works (led blinking and also serial), but leds-on.bin really doesn't. Before it switched on LEDs 0 to 3, but now, LEDs 0 to 3 flash briefly, but then just LED0 stays on.

I've also tried some examples loaded from Arduino IDE (blinking LED) and it also does nothing (although it might be an unrelated issue, let me check if it isn't really a bug in leds-on.bin).

**Comment by Obijuan** [comment]
I've updated firmware/soc-demo/src-/leds-on.bin   Now all the LEDs are turned on (and they stay ON all the time)  
I've tested it on my Alhambra-II board and it works ok

Please, check and confirm that all the LEDs are on

(If you want to have a different value displayed on the LEDs, just edit the leds-on.c file, compile it and flash it)

**Comment by garretraziel** [comment]
Yeah, ok, it works now. Closing. Thanks!

**Comment by Obijuan** [comment]
Great! Thanks! 😃️
