### ISSUE TITLE
What is the core's configuration

### ISSUE THREAD

**Issue by pedro-javierf** [Obijuan/RISC-V-FPGA#7]
Hi,

I've looked at the project and seen it is based on the https://github.com/YosysHQ/picorv32 which can be configured as RV32E, RV32I, RV32IC, RV32IM, or RV32IMC core, and optionally contain a built-in interrupt controller.

Which of these configurations is the one present on the Alhambra II implementation?

**Comment by Obijuan** [comment]
The core is RV32I

But the others can be implemented easily
