### ISSUE TITLE
soc-rars-MMIO-2-ports.ice & iceprog en Windows.

### ISSUE THREAD

**Issue by Democrito** [Obijuan/RISC-V-FPGA#9]
Hola Juan,

dejo constancia de lo que comenté en el foro: (estoy en plataforma Windows)

* en soc-rars-MMIO-2-ports.ice da error al sintetizar. (estoy en plataforma Windows)
* en soc-rars-MMIO-1-ports.ice NO da error al sintetizar. Funciona bien.

Por otra parte, antiguamente para subir un binario (file.bin) sólo era necesario copiar y pegar "iceprog.exe" en el mismo lugar que estuviera el archivo binario. Ahora ya no es así, hay que tener en la misma carpeta los siguiente archivos para que no dé error (de lo contrario pide una dll que no encuentra y aconseja reinstalar, pero reinstalar no es necesario)

- iceprog.exe
- libftdi1.dll
- libusb-1.0.dll

Con esos tres archivos (que están en una subcarpeta dentro de apio) desaparece el problema y te permite subir el binario de turno, al igual que antiguamente, sólo que en vez de un programa, ahora es necesario el programa y que le acompañe las dos bibliotecas.

Saludos!

**Comment by Obijuan** [comment]
Gracias Demócrito!

El error en soc-rars-MMIO-2-ports ya está arreglado: Se pueden sintetizar y cargar sin problemas
He comprobado los otros dos cores, y funcionan perfecto

Las nuevas toolchains no están compiladas de forma estática, por lo que siempre tienen que ir acompañadas de sus correspondientes dependencias (.dll para windows). Con copiar los ficheros que has indicado en un lugar del path te funcionará correctamente

Otra opción es instalar apio directamente (que funciona en paralelo al apio de icestudio) y ejecutar el comando

```
apio raw "iceprog -o 1M fichero.bin"
```
En este caso no tienes que copiar el .exe ni las biblotecas a ningún sitio (se usan las instaladas ya por apio)

Lo dejo aquí sólo como referencia, la instalación de apio en windows está documentada en este enlace:

https://github.com/FPGAwars/apio/wiki/Quick-start#windows-10

Como ya está solucionado el problema cierro la issue

¡Muchas gracias Demócrito! 🙂️
